### PR TITLE
Widen bus

### PR DESCRIPTION
**Pull request by miketbush**
add in basic bus widening code

### CODE REVIEW

**Comment by raidersan** [comment]
Hi Mike,

I have noticed you have revamped the project structure entirely, which is great…. But, I struggle to get this new multi level setup to work with IntelliJ. What IDE do you use?
Out of the box I cannot run the example in the README. I assume you want ppl to run this from the java/dist folder? Trying to debug it, I think the path to the config needs to be modified to --config demo/juse/Z80A.system
Do you always need to run it through a demo path? What command would you run to get a C64 screen? From what folder. Sorry, probably getting too old for this but I am not fully understanding the demo concept and all that needs to go in there. 

Regards,
Jean

**Comment by miketbush** [comment]
Hi,

I am out, but will give you a full writeup later tonight.  The "demo" mode
is just to give you something you can run without assuming, say a C64 or a
Spectrum.  If you run the jar with --demo it creates the demo directory in
the current directory so it has some binaries to pick up.  The --config
option allows you to specify a .system file with all the options.

**Comment by miketbush** [comment]
I will get that doc out tonight.  I forgot it was US Biz Tax time.   :(

**Comment by raidersan** [comment]
On my side I have finally managed to get the code going with IntelliJ, for the most at least. Not fun to read tons of configuration documentation for 2 days but that is what happens when you haven’t used advanced toolset for a long time.
It would be good to have some basic build and run instructions in the readme, stating you use eclipse yourself. For somebody who wants to pick it up it will save them a lot of time. I think it would be great to have a few examples such as the C64 going as well.
Well done for the work btw, I had a look at the concept and it is light years ahead of where it was, I like the configuration and extensions concepts. Not sure mine work yet but I’ll experiment a bit when I get to successfully run one of the system included.

JF

**Comment by raidersan** [comment]
Okay I’ll give you something to chew on - Still trying to run c64.system and failing, I believe I have the right configuration in my IDE and can debug. I also believe the c64.system is outdated and didn’t get migrated with your new package structure.
Attached is an updated one I believe should work BUT…
I am still getting a stack trace which might be a remnant of a change you made in a generic class and not in its equivalent C64 Implementation, just a hunch and I got the limit of brain absorption for today, thought you might know pretty quickly what it is.

I run with " --config demo/C64.system”, but get the following error (with the new C64.system, might be an error from my part in its modification)

Initializing bus device:RAM
Initializing bus device:CIA
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:70)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at com.juse.emulator.util.config.SystemConfig.initBusDevice(SystemConfig.java:239)
	at com.juse.emulator.SystemEmulatorEntry.init(SystemEmulatorEntry.java:125)
	at com.juse.emulator.SystemEmulatorEntry.<init>(SystemEmulatorEntry.java:82)
	at com.juse.emulator.SystemEmulatorEntry.main(SystemEmulatorEntry.java:420)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to com.juse.emulator.interfaces.BusAddressRange
	at java.base/java.lang.Class.cast(Class.java:3946)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	... 6 more

￼

**Comment by miketbush** [comment]
Hi,

Still working on the docs, but to get you started, I have updated the /etc
directory with an updated Eclipse (which is what I use) and an IntelliJ
config too.

You can use those files to update your project for the deps and with a
launch example.

Watch for more doc updates.  I am trying to hurry, but have some job
related things eating my time.

Thanks,
Mike

**Comment by miketbush** [comment]
Sorry, those changes are still in the alt branch, "example-ui-enhancement"

**Comment by raidersan** [comment]
No worries, I have little time myself and I am now spending all of it finding a tool that can help me reverse engineer in UML the various packages so that one can get over the complexity and grasp the concept. The dynamic instantiation doesn’t make it easy to follow the hierarchy of all those classes. Maybe if I get anywhere decent, those diagrams could be published in the repository
BTW, I think the C64 system is erroring because you CIA device in the C64.system file only has one address specified where as its constructors expects a BusAdressRangeImpl that expects either a start address, length and alignment or a low and high address. Me thinks, but could be wrong

Here is the entry in the C64.system file
bus=CIA,0x0000DC00

And the 2 constructors it could run:

￼

JF


When you try to cast the CIA class into

**Comment by miketbush** [comment]
Yup I pushed a couple fixes and a new C64.system in thr demo/juse directory.

**Pull request merged**
