### PR TITLE
Separate concerns

### PR DESCRIPTION
**Pull request by miketbush**
Decouple the rest of the project and added some example extensions.  There is a Z80A and a green UI.

### CODE REVIEW

**Comment by raidersan** [comment]
Hi Mike, 

On the latest build: 

/Users/jean/Dev/Java-6502-Emulator4/src/com/hadden/emulator/ui/SystemEmulatorEntry.java:6:33
java: package com.hadden.util.system.io does not exist

**Comment by miketbush** [comment]
It is fixed now.  Sorry about that.

**Comment by raidersan** [comment]
Hi Mke, I still cannot see com.hadden.util

￼

**Comment by miketbush** [comment]
Sorry!  I will fix it asap.  I think the build file needs updating.

**Comment by miketbush** [comment]
Ok it is fixed.  Somehow I lost that file in the branches.

**Pull request merged**
